name = "creatodo"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "creatodo-db"
database_id = "57c3aeb1-68ca-4a13-bc6e-3a328e741772"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "creatodo-storage"

[ai]
binding = "AI"

# Set REMOVE_BG_API_KEY as a secret:  wrangler pages secret put REMOVE_BG_API_KEY
